version: "3.8"

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8030:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
    depends_on:
      - mysql
      - php
    networks:
      - app-network

  php:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG:
        client_host=host.docker.internal
        start_with_request=yes
      XDEBUG_TRIGGER: 'yes'
  mysql:
    image: mysql:8.0
    ports:
      - "1337:3306"
    env_file:
      - env/mysql.env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  composer:
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/laravel
  artisan:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    entrypoint: ["php", "/var/www/laravel/artisan"]

volumes:
  db_data:

#Docker Networks
networks:
  app-network:
    driver: bridge

